import React, { useEffect, useState } from 'react'
import courtService from '@/service/courtService'
import { formatCurrency, formatDate, formatTime } from '@/utils/format'
import useToast from '@/components/ui/Toast'
import Button from '@/components/ui/Button'
import Card, { CardContent, CardHeader } from '@/components/ui/Card'
import { Skeleton } from '@/components/ui/Skeleton'
import { Users, Trophy, Sparkles, CheckCircle2, UserPlus, Calendar } from 'lucide-react'

export const MemberSocial = () => {
  const toast = useToast()
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)
  const [joiningId, setJoiningId] = useState(null)

  const fetchSessions = async () => {
    setLoading(true)
    try {
      const data = await courtService.getSocialSessions()
      setSessions(data || [])
    } catch (err) {
      toast.error('Failed to load social sessions')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchSessions()
  }, [])

  const handleJoin = async (session) => {
    setJoiningId(session.id)
    try {
      await courtService.joinSocialSession(session.id)
      toast.success('Joined Friday Social Play session!')
      fetchSessions()
    } catch (err) {
      if (err.code === 'SESSION_FULL') {
        toast.error('This social session is full.')
      } else if (err.code === 'ALREADY_JOINED') {
        toast.info('You have already joined this session.')
      } else {
        toast.error(err.message || 'Failed to join session')
      }
    } finally {
      setJoiningId(null)
    }
  }

  return (
    <div className="space-y-6 font-sans">
      <div className="border-b border-slate-200 pb-5">
        <span className="text-xs font-bold uppercase tracking-widest text-indigo-700">
          Club Mixer
        </span>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 mt-1">
          Friday Social Play Lobby
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 mt-1">
          Weekly doubles rotations and padel mixers. Meet fellow champions and rotate courts every 20 minutes.
        </p>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[...Array(2)].map((_, i) => (
            <Skeleton key={i} className="h-64 rounded-2xl" />
          ))}
        </div>
      ) : sessions.length === 0 ? (
        <div className="p-16 text-center bg-white rounded-2xl border border-slate-200 space-y-4">
          <Users className="w-12 h-12 text-slate-300 mx-auto" />
          <div>
            <h3 className="font-bold text-slate-800 text-base">No upcoming Friday sessions</h3>
            <p className="text-xs text-slate-400 mt-1">
              Social sessions for next Friday are generated by front desk management.
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {sessions.map((s) => {
            const spotsLeft = (s.capacity || 8) - (s.joined || 0)
            const isFull = spotsLeft <= 0

            return (
              <Card key={s.id} hover className="border-slate-200 overflow-hidden">
                <div className="bg-gradient-to-r from-indigo-900 to-slate-900 text-white p-5">
                  <div className="flex items-center justify-between">
                    <span className="px-2.5 py-1 rounded-full bg-indigo-500/30 text-indigo-200 text-[10px] font-bold uppercase tracking-wider">
                      {s.court?.sport || 'Social Match'}
                    </span>
                    <span className="text-xs font-bold text-amber-400">
                      {spotsLeft > 0 ? `${spotsLeft} Spots Available` : 'Session Full'}
                    </span>
                  </div>
                  <h3 className="text-lg font-bold mt-2">{s.title || 'Friday Night Social Mixer'}</h3>
                  <p className="text-xs text-slate-300 mt-0.5">
                    {formatDate(s.startAt)} • {formatTime(s.startAt)} – {formatTime(s.endAt)}
                  </p>
                </div>

                <CardContent className="p-5 space-y-4">
                  <div className="flex items-center justify-between text-xs p-3 rounded-lg bg-slate-50 border border-slate-100">
                    <span className="text-slate-600">Capacity & Roster:</span>
                    <strong className="text-slate-800">
                      {s.joined || 0} / {s.capacity || 8} Players
                    </strong>
                  </div>

                  <div className="flex items-center justify-between text-xs p-3 rounded-lg bg-slate-50 border border-slate-100">
                    <span className="text-slate-600">Price for Gold Pass:</span>
                    <strong className="text-emerald-700">₹0.00 (Complimentary)</strong>
                  </div>

                  <Button
                    variant="lawn"
                    size="md"
                    disabled={isFull}
                    loading={joiningId === s.id}
                    onClick={() => handleJoin(s)}
                    className="w-full font-bold justify-center"
                  >
                    {isFull ? 'Session is Full' : 'Join Friday Social Session'}
                  </Button>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}

export default MemberSocial
