import React, { useEffect, useState } from 'react'
import courtService from '@/service/courtService'
import authService from '@/service/authService'
import { formatDate, formatTime } from '@/utils/format'
import useToast from '@/components/ui/Toast'
import Button from '@/components/ui/Button'
import Card, { CardContent } from '@/components/ui/Card'
import { Skeleton } from '@/components/ui/Skeleton'
import { Users } from 'lucide-react'

export const MemberSocial = () => {
  const toast = useToast()
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)
  const [joiningId, setJoiningId] = useState(null)
  const [membership, setMembership] = useState(null)

  const fetchSessions = async () => {
    setLoading(true)
    try {
      const data = await courtService.getSocialSessions()
      setSessions(data || [])
    } catch {
      toast.error('Failed to load social sessions')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchSessions()
    authService.me().then((res) => {
      if (res?.membership) setMembership(res.membership)
    }).catch(() => {})
  }, [])

  const hasActiveMembership = Boolean(membership && (membership.status === 'active' || !membership.status))

  const handleJoin = async (session) => {
    setJoiningId(session.id)
    try {
      await courtService.joinSocialSession(session.id)
      toast.success('Joined Friday Social Play session!')
      fetchSessions()
    } catch (err) {
      if (err.code === 'SESSION_FULL') {
        toast.error('This social session is full.')
      } else if (err.code === 'ALREADY_JOINED') {
        toast.info('You have already joined this session.')
      } else {
        toast.error(err.message || 'Failed to join session')
      }
    } finally {
      setJoiningId(null)
    }
  }

  return (
    <div className="space-y-6 font-sans">
      <div className="border-b border-white/10 pb-5">
        <span className="px-3 py-1 rounded-full text-[11px] font-black uppercase tracking-widest bg-[#CCFF00] text-black">
          Club Mixer
        </span>
        <h1 className="text-2xl sm:text-3xl font-extrabold uppercase tracking-tight text-white mt-3">
          Friday Social Play Lobby
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Weekly doubles rotations and padel mixers. Meet fellow champions and rotate courts every 20 minutes.
        </p>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[...Array(2)].map((_, i) => (
            <Skeleton key={i} className="h-64 rounded-2xl bg-white/5" />
          ))}
        </div>
      ) : sessions.length === 0 ? (
        <div className="p-16 text-center bg-[#111418] rounded-2xl border border-white/10 space-y-4">
          <Users className="w-12 h-12 text-slate-600 mx-auto" />
          <div>
            <h3 className="font-bold text-white text-base">No upcoming Friday sessions</h3>
            <p className="text-xs text-slate-400 mt-1">
              Social sessions for next Friday are generated by front desk management.
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {sessions.map((s) => {
            const spotsLeft = (s.capacity || 8) - (s.joined || 0)
            const isFull = spotsLeft <= 0

            return (
              <Card key={s.id} hover className="border-white/10 bg-[#111418] overflow-hidden hover:border-[#CCFF00]/40 transition-all">
                <div className="bg-gradient-to-r from-[#161B22] to-[#0D1117] text-white p-5 border-b border-white/10">
                  <div className="flex items-center justify-between">
                    <span className="px-2.5 py-1 rounded-full bg-[#CCFF00]/15 text-[#CCFF00] border border-[#CCFF00]/30 text-[10px] font-black uppercase tracking-wider">
                      {s.court?.sport || 'Social Match'}
                    </span>
                    <span className="text-xs font-black text-[#CCFF00]">
                      {spotsLeft > 0 ? `${spotsLeft} Spots Available` : 'Session Full'}
                    </span>
                  </div>
                  <h3 className="text-lg font-bold uppercase tracking-tight text-white mt-2">{s.title || 'Friday Night Social Mixer'}</h3>
                  <p className="text-xs text-slate-400 mt-0.5 font-mono">
                    {formatDate(s.startAt)} • {formatTime(s.startAt)} – {formatTime(s.endAt)}
                  </p>
                </div>

                <CardContent className="p-5 space-y-4">
                  <div className="flex items-center justify-between text-xs p-3 rounded-xl bg-white/5 border border-white/10">
                    <span className="text-slate-400">Capacity & Roster:</span>
                    <strong className="text-white font-mono">
                      {s.joined || 0} / {s.capacity || 8} Players
                    </strong>
                  </div>

                  <div className="flex items-center justify-between text-xs p-3 rounded-xl bg-white/5 border border-white/10">
                    <span className="text-slate-400">
                      {hasActiveMembership ? `Price for ${membership?.plan_name || 'Member'}:` : 'Price for Club Guest:'}
                    </span>
                    <strong className={hasActiveMembership ? 'text-[#CCFF00] font-mono font-bold' : 'text-white font-mono font-bold'}>
                      {hasActiveMembership ? '₹0.00 (Complimentary)' : 'Standard Entry Fee'}
                    </strong>
                  </div>

                  <Button
                    variant="volt"
                    size="md"
                    disabled={isFull}
                    loading={joiningId === s.id}
                    onClick={() => handleJoin(s)}
                    className="w-full font-black justify-center"
                  >
                    {isFull ? 'Session is Full' : 'Join Friday Social Session'}
                  </Button>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}

export default MemberSocial
